### ISSUE TITLE
Package manager dependency indexes

### ISSUE THREAD

**Issue by roaldarbol** [BrianPugh/belay#43]
I've not used the package manager yet, but just based on the documentation it seems that you have to specify URLs to repos. Poetry indexes PyPi, so maybe it could be an idea to do something similar to automatically index both PyPi and micropython-lib? E.g. having
```toml
[tools.belay.dependencies.pip]
toml = "^0.10.2"

[tools.belay.dependencies.mip]
logging = "^0.5.2"
```
or a more Poetry compatible version:
```toml
[tools.belay.group.pip.dependencies]
toml = "^0.10.2"

[tools.belay.group.mip.dependencies]
logging = "^0.5.2"
```

And since Micropython packages can also be in places like [pycopy](https://github.com/pfalcon/pycopy-lib) maybe thinking about how to implement specify indexes more generally (like secondary indexes in Poetry) would be worthwhile. 😊
